### ISSUE TITLE
Support new Slack update

### ISSUE THREAD

**Issue by asportnoy** [dracula/slack#13]
Slack did a big re-design including with their theme system, so Dracula will need to be updated to work with that.

**Comment by chessmango** [comment]
I tried taking a stab at this, but it seems that there's explicitly a limited colour palette (for now?)
Looking at Slack's [FAQ](https://slack.com/intl/en-gb/help/articles/16764236868755-An-overview-of-Slacks-new-design#01H806999DPXEB44PQKYQTQEW6) it seems this is the 'new normal'.

The available colours, for what they're worth, are:
#de4e2b
#d65d30
#e96825
#cf6c02
#d38d00
#dea900
#729c1a
#379e15
#2fa659
#20a271
#2392a2
#0e9dd3
#2985cd
#4864d2
#c474d3
#c05b8c
#ef3e75
#f2606a
#9c6c39
#7c7a7f

**Comment by asportnoy** [comment]
Yeah I talked to Slack support about this. They removed the color picker, they removed a bunch of the options, and they removed the import button even though you can still share a theme. Thoroughly disappointed in this update. Unfortunately unless they change something I think Dracula Slack is dead 😕.

**Comment by a4sr3s** [comment]
Should have never rebooted slack... miss Dracula already. Hopefully they push an update to get this working again.

**Comment by michxymi** [comment]
I had a bit of a play with the updated slack client and get it closer to the original look.

The problem has to do with the expect string for theme formatting. The original theme had 8 values while with the current version 10 values are expected. So by adding two more values on the original string list, for example:

`#282A36,#44475A,#44475A,#8BE9FD,#6272A4,#FFFFFF,#50FA7B,#FF5555,#44475A,#44475A
`

and paste it in `Slack/Settings/Themes/Import Theme` I get a similar look. Hopefully there is some documentation about what each value represents, otherwise I'll have to do some reverse engineering to work it out.

Once I'm happier with the way it looks I'll submit a PR to maintainers for review.

**Comment by mrmeku** [comment]
@michxymi You're my hero today

**Comment by luxonauta** [comment]
Can you make a PR for a test? 🤔

**Comment by michxymi** [comment]
> Can you make a PR for a test? 🤔

Just made one. I haven't been able to exactly work out which colour values are mapping to which element so I opted to keep the greyish colour (#44475A, #44475A) as the two additional values required in the theme string. One thing that I don't see in comparison with the original is the electric blue highlight on the text but I haven't been able to fix that.

**Comment by D-u-c-k-s-e-l** [comment]
Digging into this issue, this was "fixed" two years ago (#8) by editing `dracula.md` to be the ten value color scheme.
Unfortunately, this did not get applied to the instructions.
I have created #15 which adds this to the instructions.
It seems that the last two values correspond to the nav background and nav foreground (respectively).

**Comment by quagliato** [comment]
I have just merged @D-u-c-k-s-e-l's PR. The problem should be solved now.

Thank you all! :)
